[NbConvertApp] Converting notebook scarlet_tutorial.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: lsst
[NbConvertApp] ERROR | Error while converting 'scarlet_tutorial.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 381, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 424, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load the sample images
idx = 53
file_path = "/project/shared/data/testdata_deblender/real_data/hsc_cosmos/not_matched"
files = os.listdir(file_path)
data = np.load(os.path.join(file_path, files[idx]))
images = data["images"]
weights = data["weights"]
peaks = data["peaks"]
psfs = data["psfs"]
filters = ["G", "R", "I", "Z", "Y"]
# Only a rough estimate of the background is needed
# to initialize and resize the sources
bg_rms = np.std(images, axis=(1,2))
print("Background RMS: {0}".format(bg_rms))

# Use Asinh scaling for the images
norm = AsinhMapping(minimum=images.min(), stretch=images.max()/20, Q=10)
# Convert the image to an RGB image
img_rgb = scarlet.display.img_to_rgb(images, norm=norm)
plt.imshow(img_rgb)
plt.title("Image: {0}".format(idx))
for k, src in enumerate(peaks):
    plt.text(src[0], src[1], str(k), color="blue")
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-89d60ee7451c>[0m in [0;36m<module>[0;34m[0m
[1;32m     17[0m [0mnorm[0m [0;34m=[0m [0mAsinhMapping[0m[0;34m([0m[0mminimum[0m[0;34m=[0m[0mimages[0m[0;34m.[0m[0mmin[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mstretch[0m[0;34m=[0m[0mimages[0m[0;34m.[0m[0mmax[0m[0;34m([0m[0;34m)[0m[0;34m/[0m[0;36m20[0m[0;34m,[0m [0mQ[0m[0;34m=[0m[0;36m10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;31m# Convert the image to an RGB image[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 19[0;31m [0mimg_rgb[0m [0;34m=[0m [0mscarlet[0m[0;34m.[0m[0mdisplay[0m[0;34m.[0m[0mimg_to_rgb[0m[0;34m([0m[0mimages[0m[0;34m,[0m [0mnorm[0m[0;34m=[0m[0mnorm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0mplt[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mimg_rgb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m"Image: {0}"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0midx[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/lsst/software/stack/stack/miniconda3-4.5.12-1172c30/Linux64/scarlet/lsst-dev-g62a773d79d+5/lib/python/scarlet-0.3-py3.7-linux-x86_64.egg/scarlet/display.py[0m in [0;36mimg_to_rgb[0;34m(img, norm, fill_value, filter_indices)[0m
[1;32m    185[0m             [0mrgb[0m[0;34m[[0m[0mb[0m[0;34m][0m [0;34m=[0m [0mnorm[0m[0;34m[[0m[0mb[0m[0;34m][0m[0;34m([0m[0mimg[0m[0;34m[[0m[0mb[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    186[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 187[0;31m         [0mrgb[0m [0;34m=[0m [0mnorm[0m[0;34m([0m[0mimg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    188[0m     [0;32mif[0m [0mhasattr[0m[0;34m([0m[0mrgb[0m[0;34m,[0m[0;34m"mask"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    189[0m         [0mrgb[0m [0;34m=[0m [0mrgb[0m[0;34m.[0m[0mfilled[0m[0;34m([0m[0mfill_value[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'AsinhMapping' object is not callable
TypeError: 'AsinhMapping' object is not callable

